export const POEM_VIDEOS = [
  {
    id: "daffodils",
    scene: "meadow",
    title: "Daffodils",
    titleUrdu: "ڈیفوڈلز",
    author: "William Wordsworth",
    minutes: 1,
    linesEn: [
      "I wandered lonely as a cloud",
      "That floats on high o'er vales and hills,",
      "When all at once I saw a crowd,",
      "A host, of golden daffodils;",
      "Beside the lake, beneath the trees,",
      "Fluttering and dancing in the breeze.",
    ],
    linesUr: [
      "میں تنہا ایک بادل کی طرح بھٹکتا رہا",
      "جو وادیوں اور پہاڑیوں کے اوپر تیرتا ہے،",
      "جب اچانک میں نے ایک ہجوم دیکھا،",
      "سنہرے پھولوں کا ایک لشکر؛",
      "جھیل کے کنارے، درختوں کے نیچے،",
      "ہوا میں پھڑپھڑاتے اور ناچتے ہوئے۔",
    ],
  },
  {
    id: "if",
    scene: "mountain",
    title: "If —",
    titleUrdu: "اگر",
    author: "Rudyard Kipling",
    minutes: 1,
    linesEn: [
      "If you can keep your head when all about you",
      "Are losing theirs and blaming it on you,",
      "If you can trust yourself when all men doubt you,",
      "But make allowance for their doubting too;",
      "If you can wait and not be tired by waiting,",
      "Yours is the Earth and everything that's in it.",
    ],
    linesUr: [
      "اگر تم اپنا حوصلہ برقرار رکھ سکو، جب سب اپنا کھو بیٹھیں",
      "اور اس کا الزام تم پر رکھیں،",
      "اگر تم خود پر بھروسہ کر سکو جب سب شک کریں،",
      "مگر ان کے شک کو بھی سمجھ سکو؛",
      "اگر تم انتظار کر سکو اور انتظار سے تھکے نہ",
      "تو زمین اور اس میں سب کچھ تمہارا ہے۔",
    ],
  },
  {
    id: "twinkle",
    scene: "night",
    title: "Twinkle, Twinkle, Little Star",
    titleUrdu: "ٹوٹکن، ٹوٹکن، چھوٹا ستارہ",
    author: "Jane Taylor",
    minutes: 1,
    linesEn: [
      "Twinkle, twinkle, little star,",
      "How I wonder what you are!",
      "Up above the world so high,",
      "Like a diamond in the sky.",
      "Twinkle, twinkle, little star,",
      "How I wonder what you are!",
    ],
    linesUr: [
      "ٹمٹماتا، ٹمٹماتا، چھوٹا ستارہ،",
      "میں کیا جانوں تو کیس ہے!",
      "دنیا کے اوپر اتنا اونچا،",
      "آسمان میں ہیرے جیسا۔",
      "ٹمٹماتا، ٹمٹماتا، چھوٹا ستارہ،",
      "میں کیا جانوں تو کیس ہے!",
    ],
  },
  {
    id: "lab-pe-dua",
    scene: "mosque",
    title: "Lab Pe Aati Hai Dua",
    titleUrdu: "لب پہ آتی ہے دعا",
    author: "Allama Iqbal",
    urdu: true,
    minutes: 1,
    linesEn: [
      "On my lips a prayer arrives —",
      "make my eyes light up with the Quran,",
      "let my heart know no faith but Yours,",
      "and my hands reach for prayer.",
      "Grant me, Lord, a life like this:",
      "a lamp that lights the way for others.",
    ],
    linesUr: [
      "لب پہ آتی ہے دعا بن کے تمنا میری",
      "زندگی شمع کی طرح روشن اور جلے بھلا میری",
      "ہدایت دے مجھ کو اے تو اپنے بندے میرے",
      "اور بنا دے مجھ کو اے خدا سچا میرا",
      "دیدار اپنا کر دے تو نورِ رہ ہو میرا",
      "یہی ہے سودا میرا یہی ارمغان میرا",
    ],
  },
  {
    id: "humpty",
    scene: "mountain",
    title: "Humpty Dumpty",
    titleUrdu: "ہمپی ڈمپی",
    author: "Traditional",
    minutes: 1,
    linesEn: [
      "Humpty Dumpty sat on a wall,",
      "Humpty Dumpty had a great fall;",
      "All the king's horses and all the king's men",
      "Couldn't put Humpty together again.",
    ],
    linesUr: [
      "ہمپی ڈمپی دیوار پر بیٹھا،",
      "ہمپی ڈمپی زور سے گرا؛",
      "بادشاہ کے سارے گھڑے اور سارے سپاہی،",
      "اسے دوبارہ جوڑ نہ سکے۔",
    ],
  },
  {
    id: "baa-baa",
    scene: "meadow",
    title: "Baa Baa Black Sheep",
    titleUrdu: "بھیں بھیں کالا بھیڑ",
    author: "Traditional",
    minutes: 1,
    linesEn: [
      "Baa, baa, black sheep,",
      "Have you any wool?",
      "Yes, sir, yes, sir,",
      "Three bags full —",
      "One for the master,",
      "One for the dame,",
      "And one for the little boy",
      "Who lives down the lane.",
    ],
    linesUr: [
      "بھیں بھیں، کالے بھیڑ،",
      "کیا تمہارے پاس اون ہے؟",
      "جی ہاں، جی ہاں،",
      "تین بوریاں بھریں —",
      "ایک مالک کے لیے،",
      "ایک بیگم کے لیے،",
      "اور ایک چھوٹے بچے کے لیے",
      "جو گلی میں رہتا ہے۔",
    ],
  },
  {
    id: "mary-lamb",
    scene: "meadow",
    title: "Mary Had a Little Lamb",
    titleUrdu: "میری کے پاس ایک چھوٹا بھیڑ",
    author: "Traditional",
    minutes: 1,
    linesEn: [
      "Mary had a little lamb,",
      "Its fleece was white as snow,",
      "And everywhere that Mary went,",
      "The lamb was sure to go.",
      "It followed her to school one day,",
      "Which was against the rule;",
      "It made the children laugh and play",
      "To see a lamb at school.",
    ],
    linesUr: [
      "میری کے پاس ایک چھوٹا بھیڑ تھا،",
      "جس کا پشم برف جیسا سفید تھا،",
      "میری جہاں بھی جاتی،",
      "بھیڑ ساتھ ساتھ چلتا تھا۔",
      "ایک دن وہ اسے سکول لے گئی،",
      "جو قاعدے کے خلاف تھا؛",
      "بچوں کو دیکھ کر ہنسی آئی",
      "سکول میں بھیڑ دیکھ کر۔",
    ],
  },
  {
    id: "sitarey",
    scene: "night",
    title: "Sitaron Ki Kahani",
    titleUrdu: "ستاروں کی کہانی",
    author: "Kitaabistan Kids",
    urdu: true,
    minutes: 1,
    linesEn: [
      "When the moon climbs up the sky,",
      "Little stars come out to play;",
      "They blink, they wink, they shine so bright,",
      "Guarding us the whole night.",
      "Sleep now, little friend, and see —",
      "Morning brings the sun to thee.",
    ],
    linesUr: [
      "جب چاند آسمان پر چڑھے،",
      "تو چھوٹے ستارے کھیلنے آئیں؛",
      "وہ ٹمٹماتے، دیکھتے اور کتنے روشن ہیں،",
      "پوری رات ہماری حفاظت کرتے ہیں۔",
      "اب سو جاؤ، چھوٹے دوست، اور دیکھو —",
      "صبح آپ کے لیے سورج لائے گی۔",
    ],
  },
];

export function findPoem(id) {
  return POEM_VIDEOS.find((p) => p.id === id) || null;
}
